# Generated by Django 4.2.3 on 2023-07-31 17:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KR'),
        ),
    ]
