# Generated by Django 4.2.3 on 2023-08-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='categories',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellers.market'),
            preserve_default=False,
        ),
    ]
