# Generated by Django 4.2.3 on 2023-08-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_market_categories_menucategory_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
