# Generated by Django 4.2.3 on 2023-08-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='sellers.menucategory'),
        ),
        migrations.AddField(
            model_name='market',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode/'),
        ),
        migrations.AlterField(
            model_name='market',
            name='register',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.register'),
        ),
    ]
