# Generated by Django 4.2.3 on 2023-08-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_market_categories_market_qr_alter_market_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='sellers.menucategory'),
        ),
    ]
