# Generated by Django 4.2.3 on 2023-08-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_register_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='close',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='market',
            name='time',
            field=models.TextField(default='연중무휴'),
        ),
    ]
