# Generated by Django 4.2.3 on 2023-08-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='need',
            field=models.TextField(blank=True, null=True),
        ),
    ]
