# Generated by Django 4.2.3 on 2023-08-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_payment_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
