# Generated by Django 4.2.4 on 2023-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_option'),
        ('buyers', '0007_remove_cart_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='sellers.option'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_type',
            field=models.CharField(default='매장식사', max_length=10),
        ),
    ]
