# Generated by Django 4.2.3 on 2023-08-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_option'),
        ('buyers', '0008_cartitem_options_payment_order_type'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='options',
        #     field=models.ManyToManyField(blank=True, to='sellers.option'),
        # ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.menu')),
                ('options', models.ManyToManyField(blank=True, to='sellers.option')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyers.payment')),
            ],
        ),
    ]
