<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-17 06:59
=======
# Generated by Django 4.2.3 on 2023-08-17 12:22
>>>>>>> a273061acff72d0e11b458b2f4687ad1328b2fb6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_option'),
        ('buyers', '0008_cartitem_options_payment_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='sellers.option'),
        ),
    ]
