# Generated by Django 4.2.3 on 2023-08-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_option'),
        ('buyers', '0008_cartitem_options_payment_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='sellers.option'),
        ),
    ]
